source "https://rubygems.org"

ruby "2.2.2"

gem "sinatra"
gem "typhoeus"
gem "sinatra-activerecord"
gem "pg"
gem "rake"
gem "awesome_print"
gem "koala", "~> 2.2"
gem "clockwork"
gem "colorize"
gem "puma"
gem "sentry-raven"
